# Project information
site_name: Блок А - ФК Зенит
site_url: https://thomassuedbroecker.github.io/How-to-install-MkDocs-on-Mac-and-setup-integration-with-GitHub
site_author: Pavskii Artem

# Repository
docs_dir: docs

# Navigation
nav:
  - Welcome:
    - Overview: README.md 
  - Steps:
    - 1 MkDocs installation on Mac: steps/1-MkDocs-installation-on-Mac.md 
    - 2 Verify your documentation and build the pages: steps/2-Verify-your-documentation-and-build-the-pages.md
    - 3 Setup the integration to your GitHub project: steps/3-Setup-the-integration-to-your-GitHub-project.md

# Theme
theme:
  name: material
  language: ru
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/library
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
#     - media: "(prefers-color-scheme: light)" 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Перейти на тёмную сторону
#     - media: "(prefers-color-scheme: dark)" 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Перейти на светлую сторону
    primary: deep purple
    accent: deep purple

# Plugins
plugins:
  - git-revision-date
  - search:
      lang: ru

# Extra
extra:
  generator: false

# Customization
copyright: 2022 &copy; Блок А - ФК Зенит

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
