# Project information
site_name: Портал стюардов блока А
site_description: Единое информационное пространство для стюардов блока А стадиона Газпром Арена
site_url: https://callistoboy.github.io/stewards-a-book
site_author: Pavskii Artem

# Repository
docs_dir: docs
extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css

# Theme
theme:
  name: material
  custom_dir: 'custom/'
  logo: 'assets/images/a-logo-white.svg'
  language: ru
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  icon:
    logo: material/library
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Нокс!
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Люмус!

# Plugins
plugins:
  - macros:
      module_name: modules
  - search:
      lang: ru
      lang: en

# Extra
extra:
  generator: false

# Customization
copyright: 2022 &copy; Блок А - ФК Зенит

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Navigation
nav:
  - Общая информация:
    - О блоке: articles/basic/block.md
    - Руководство: articles/basic/management.md
    - Документы стюарда: articles/basic/docs.md
    - Нормативно-правовые документы: articles/basic/laws.md
  - Правила:
    - Для стюардов:
      - Дресс-код: articles/rules/dress-code.md
      - Кодекс стюарда: articles/rules/code.md
      - Санитарные правила: articles/rules/covid.md
      - Права и обязанности стюардов: articles/rules/rights.md
    - Для зрителей:
      - Правила поведения зрителей: articles/rules/spectators.md
      - Запрещённые предметы: articles/rules/prohibited_items.md
      - Запрещённые знаки и символы: articles/rules/prohibited_symbols.md
  - Инструкции:
    - Приложение:
      - Установка приложения: articles/app/install.md
      - Авторизация в приложении: articles/app/login.md
      - Сканирование билетов: articles/app/tickets.md
      - Возможные ошибки: articles/app/errors.md
    - Служебные инструции:
      - Эвакуация чаши: articles/manuals/evacuation.md
      - Бесхозный предмет: articles/manuals/ownerless.md
    - Процессы:
      - Внутренние трансферы: articles/manuals/transfers.md
      - Расторжение договора: articles/manuals/decline.md
  - Cервисы: 
    - articles/services.md
    - Обратная связь:
      - Описание: articles/feedback/about.md
      - Форма обратной связи: https://forms.yandex.ru/cloud/6171388724395acafe4ec871/
      - Отзывы: articles/feedback/reviews.md
      - Обсуждения: https://github.com/Callistoboy/stewards-a-book-test/discussions
    - Получение автопропуска: https://docs.google.com/forms/d/e/1FAIpQLScIWIttHdbpCohXr9g0ZqOI7nElieD47Ns4y3pjgBz5wOc7dg/viewform
    - Заказ кадровых справок: https://docs.google.com/forms/d/e/1FAIpQLSdHMvDJ93RSJU5o-UREQv6CAkctmM9l63a9rZW-peNAY7zg7w/viewform
  - Обсуждения: https://github.com/Callistoboy/stewards-a-book-test/discussions
