# Project information
site_name: Блок А - ФК Зенит
site_url: https://callistoboy.github.io/stewards-a-book-test
site_author: Pavskii Artem

# Repository
docs_dir: docs
extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css

# Theme
theme:
  name: material
  custom_dir: material/overrides
  language: ru
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  icon:
    logo: material/library
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Перейти на тёмную сторону
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Перейти на светлую сторону

# Plugins
plugins:
  - git-revision-date
  - search:
      lang: ru

# Extra
extra:
  generator: false

# Customization
copyright: 2022 &copy; Блок А - ФК Зенит

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Главная: index.md
  - Правила:
    - Дресс-код: articles/rules/dress-code.md
    - Кодекс стюарда: articles/rules/code.md
  - Приложение:
    - articles/app/install.md
    - Авторизация: articles/app/login.md
    - Сканирование билетов: articles/app/tickets.md
    - Ошибки: articles/app/errors.md
  - Общая информация:
    - О блоке: getting-started.md
    - Менеджмент: creating-your-site.md
    - Юридическая справка: browser-support.md
  - Инструкции:
    - reference/index.md
    - Эвакуация чаши: eva.md
    - Бесхозный предмет: evva2.md
  - Обратная связь:
    - insiders/index.md
    - Отзывы:
      - Installation: insiders/getting-started.md
      - Changelog: insiders/changelog.md
  - Информационные сервисы:
    - blog/index.md
    - 2021:
      - blog/2021/the-past-present-and-future.md
      - blog/2021/excluding-content-from-search.md
      - blog/2021/search-better-faster-smaller.md
