# Project information
site_name: Портал стюардов блока А
site_description: Единое информационное пространство для стюардов блока А стадиона Газпром Арена
site_url: https://callistoboy.github.io/stewards-a-book
site_author: Pavskii Artem

# Repository
docs_dir: docs
extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css

# Theme
theme:
  name: material
  custom_dir: 'custom/'
  logo: 'assets/images/a-logo-white.svg'
  language: ru
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  icon:
    logo: material/library
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Нокс!
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Люмус!

# Plugins
plugins:
  - git-revision-date
  - macros:
      module_name: modules
  - search:
      lang: ru
      lang: en

# Extra
extra:
  generator: false
  test_var: $GITHUB_JOB

# Customization
copyright: 2022 &copy; Блок А - ФК Зенит

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Правила:
    - Дресс-код: articles/rules/dress-code.md
    - Кодекс стюарда: articles/rules/code.md
    - Санитарные правила: articles/rules/covid.md
    - Права и обязанности: articles/rules/rights.md
    - Запрещенные знаки и символы: articles/rules/prohibited_symbols.md
  - Инструкции:
    - Приложение:
      - articles/app/install.md
      - Авторизация: articles/app/login.md
      - Сканирование билетов: articles/app/tickets.md
      - Возможные ошибки: articles/app/errors.md
    - Эвакуация чаши: articles/manuals/evacuation.md
    - Бесхозный предмет: articles/manuals/ownerless.md
  - Общая информация:
    - О блоке: articles/basic/block.md
    - Руководство: articles/basic/management.md
    - Документы стюарда: articles/basic/docs.md
    - Нормативно-правовые документы: articles/basic/laws.md
  - Cервисы: 
    - articles/services.md
    - Обратная связь: articles/feedback/about.md
    - Отзывы: articles/feedback/reviews.md
